// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8TNiLjLo6yU2WQTEihFHNeAOtcUPkbQo',
    appId: '1:995957647106:web:a6c955280ccc042dc0441b',
    messagingSenderId: '995957647106',
    projectId: 'nosh-62d66',
    authDomain: 'nosh-62d66.firebaseapp.com',
    storageBucket: 'nosh-62d66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmF5jo5AbozoQkrxffBJE6uwRT6488s8',
    appId: '1:995957647106:android:056bdbf2b2bc49e1c0441b',
    messagingSenderId: '995957647106',
    projectId: 'nosh-62d66',
    storageBucket: 'nosh-62d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV36hbe5hixkOlcvUuM1-qQf_kQLziGx0',
    appId: '1:995957647106:ios:4368852571bd5c6dc0441b',
    messagingSenderId: '995957647106',
    projectId: 'nosh-62d66',
    storageBucket: 'nosh-62d66.appspot.com',
    iosBundleId: 'com.example.noshNowApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV36hbe5hixkOlcvUuM1-qQf_kQLziGx0',
    appId: '1:995957647106:ios:4368852571bd5c6dc0441b',
    messagingSenderId: '995957647106',
    projectId: 'nosh-62d66',
    storageBucket: 'nosh-62d66.appspot.com',
    iosBundleId: 'com.example.noshNowApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8TNiLjLo6yU2WQTEihFHNeAOtcUPkbQo',
    appId: '1:995957647106:web:7b71b914455873dec0441b',
    messagingSenderId: '995957647106',
    projectId: 'nosh-62d66',
    authDomain: 'nosh-62d66.firebaseapp.com',
    storageBucket: 'nosh-62d66.appspot.com',
  );
}
