version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nosh_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mydb:
    
