version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nosh_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build:
      context: .
      dockerfile: nosh_now_apis/Dockerfile
    ports:
      - "5000:80"
    image: api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=$ISSUER
      - AUDIENCE=$AUDIENCE
      - KEY=$KEY

volumes:
  mydb:
    
